name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests (node ${{ matrix.node }})
    strategy:
      matrix:
        node: [ '14' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci --silent
    - run: npm run lint
